name: e_commerce_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
# ---------------------------------------------------------------------------- #
#                                    Scripts                                   #
# ---------------------------------------------------------------------------- #
scripts:
  build: "flutter build apk --release"
  test: "flutter test"
  format: "flutter format lib test"
  analyze: "flutter analyze"
  lint: "flutter analyze --no-pub --no-current-package lib"
  generate: "flutter pub run build_runner build --delete-conflicting-outputs"
  watch: "flutter pub run build_runner watch --delete-conflicting-outputs"
  clean: "flutter clean"
  run: "flutter run --no-enable-impeller"

#--------------- PACKAGES ------------------#
dependencies:
  capped_progress_indicator: ^0.0.2
  carousel_slider: ^4.2.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  firebase_storage: ^11.6.8
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_rating_bar: ^4.0.1
  get: ^4.6.5
  get_storage: ^2.1.1
  http: ^1.1.0
  iconsax_flutter: ^1.0.0
  intl: ^0.18.1
  logger: ^2.0.1
  readmore: ^2.2.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
